### ISSUE TITLE
`LinearSolve.solve` much slower than `A\b` for sparse matrices

### ISSUE THREAD

**Issue by lampretl** [SciML/LinearSolve.jl#340] opened 2023-07-03 18:12 UTC
I tried the new library LinearSolve.jl to improve the performance of solving large sparse linear systems of equations, that are implemented in SparseArrays.jl and SuiteSparse.jl. However, I noticed a significant worsening (in timing as well as accuracy):

```
using SparseArrays, LinearSolve
n, s = 10^4, 20;
A, b = sprand(n,n,s/n), sprand(n,s/n);

@time x = A \ Array(b);  
>  8.695524 seconds (94 allocations: 1.986 GiB, 0.11% gc time)
println(maximum(abs.(A*x-b)))  # check accuracy of solution
> 5.910361089433991e-11

@time (prb = init(LinearSolve.LinearProblem(A,b));   
       x = LinearSolve.solve(prb).u);
>  270.299651 seconds (449 allocations: 1.164 GiB, 0.00% gc time)
println(maximum(abs.(A*x-b)))  # check accuracy of solution
> 1.723447147217172e-7
```

Am I doing something wrong? I used Julia 1.9.1 in the REPL with LinearSolve v2.3.0.

**Comment by ChrisRackauckas** [comment] 2023-07-04 15:34
Fun one. The issue is that your matrix "isn't sparse". See:

```julia
using SparseArrays, LinearSolve
n, s = 10^4, 20;
A, b = sprand(n,n,s/n), sprand(n,s/n);

@time x = A \ Array(b); 
# 2.748556 seconds (88 allocations: 2.247 GiB, 0.15% gc time)

prb = LinearSolve.LinearProblem(A,b);
@time LinearSolve.solve(prb, UMFPACKFactorization());
# 2.583652 seconds (94 allocations: 2.250 GiB, 0.12% gc time)

@time LinearSolve.solve(prb, KLUFactorization());
# 88.481454 seconds (106.15 k allocations: 1.173 GiB, 0.00% gc time, 0.03% compilation time: 100% of which was recompilation)
```

Julia's `\` on sparse matrices is dumb and defaults to only using UMFPACK. UMFPACK is much faster than KLU for equations   because how it works is that it finds transformations to get "sufficiently dense" blocks and then does the multithreaded LAPACK LU factorization on those subsystems. Since your system is so dense, it just essentially does LAPACK on it, multithreaded and all, and is fast treating it as just a dense matrix.

But this then begs the question, how should the heuristic fix this? Of course it should take into account the amount of sparsity, but what is the cutoff?

```julia
using SparseArrays, LinearSolve, LinearAlgebra
sparsities = 2.0 .^ (-10:-1:-14)
times = map(sparsities) do s
    n = 10^4
    A, b = sprand(n,n,s), sprand(n,s);
    A = A + I
    prb = LinearSolve.LinearProblem(A,b);
    t1 = @elapsed LinearSolve.solve(prb, UMFPACKFactorization());
    t2 = @elapsed LinearSolve.solve(prb, KLUFactorization());
    t1,t2
end

using Plots
plot(sparsities,first.(times), label = "UMFPACK", xscale = :log10, yscale = :log10)
plot!(sparsities,first.(Base.tail.(times)), label = "KLU")

@show sparsities[4]
# 0.0001220703125
```

<img width="595" alt="Screenshot 2023-07-04 at 4 32 17 PM" src="https://github.com/SciML/LinearSolve.jl/assets/1814174/a9fb53a3-3d83-4bc7-b642-1ba897381993">


so around at `1e-4` probability sparsity KLU is faster. Now, that's not the only indication to consider: KLU just generally works better on smaller systems and UMFPACK is better if the system is sufficiently large and has structure, regardless of "how sparse it is" (example: tridiagonal systems or Laplacian discretizations). So this would change the heuristic from a size check to being a size and sparsity check: if the system is small enough and the sparsity is low enough use KLU, otherwise default to UMFPACK. That would fix this case and still give the faster method in most cases.

I'll make this improvement soon. Fun!

**Comment by lampretl** [comment] 2023-07-06 11:30
Glad I provided a fun example :). Hopefully my reports are useful. 

My above matrix has density 0.2%, that sounds pretty sparse to me. Any less and the matrix wouldn't be invertible, so both calls would return an error. However, it is true that the dimension `n=10^4` is small enough that it could be converted to a dense matrix and computed with other methods. This, if I understand you correctly, happens under the hood, at least for parts of the matrix. 

Hence, I tried a bigger case on my laptop with 6-core i7-8850H CPU with 64GB DDR4 RAM:
```
using SparseArrays, LinearSolve
n, s = 5*10^4, 20;   A, b = sprand(n,n,s/n), sprand(n,s/n);

@time (x = Array(A) \ Array(b));   println(maximum(abs.(A*x-b)))  # solving with a dense matrix
# 696.465488 seconds (10 allocations: 37.254 GiB, 0.00% gc time)
# 9.847483939395829e-12

@time (x = A \ Array(b));   println(maximum(abs.(A*x-b)))  
# 613.900805 seconds (87 allocations: 50.173 GiB, 0.00% gc time)
# 1.601508370363547e-10

@time (prb = init(LinearSolve.LinearProblem(A,b));  x = LinearSolve.solve(prb).u);   println(maximum(abs.(A*x-b)))
# 614.745483 seconds (449 allocations: 54.893 GiB, 0.00% gc time)
# 2.503693363742343e-10
```
Smaller difference in performance, though `A\b` is still slightly faster and more accurate. Note that for each of the 3 calls above, I rebooted Julia to empty the memory.

However, what worries me is that, as we see above, both `A\b` and `LinearSolve.solve` ***use more memory*** than if we convert A to a dense matrix and compute with that, making both methods useless. The whole point of sparse arrays is to save up on memory by not storing the abundant zeros.

I will make 2 new bug reports documenting this, one to `LinearSolve.jl` and one to `LinearAlgebra.jl`. 
Any improvement on `LinearSolve.solve`, especially for sparse matrices, would be greatly appreciated. : )

P.S. I also benchmarked Python's scipy implementation:
```
import time, numpy as np, scipy.sparse as sp
def now(): return time.time()

n, s = 10**4, 20;   A=sp.rand(n,n,s/n,"csr");   b=sp.rand(n,1,s/n,"csr"); 
t0=now();   x=sp.linalg.spsolve(A,b)[:,None];   t1=now();     print(t1-t0, np.abs(A@x-b).max())
# 473.5202627182007 2.960617861980097e-12
```
It is quite slow, though seems to use less RAM.

**Comment by Wimmerer** [comment] 2023-07-13 10:02
@ChrisRackauckas I would strongly caution optimizing against `sprand`. Especially at `0.2` sparsity, which is *really* not very sparse actually. Generally we consider something to be sparse as it gets closer to `O(n)` or `O(m)`, *not* `O(n*m)`. 

I would really welcome performance issues from real world matrices @lampretl, but hitting UMFPACk, KLU, SuperLU, Cholesky, etc with *random* ***and*** *very nearly dense* matrices is not a realistic measure of performance.

**Comment by Wimmerer** [comment] 2023-07-13 10:47
Ah okay I see I misread something somewhere, my apologies for that. I may have also crossed wires in my head because the *factors* do get at least 0.2 fill-in for all the `sprand` runs I've done with your parameters. 20% fill-in is indeed much too high on the factors (at least in my experience).

Happy to chat at JuliaCon! Message me and I'll try to find a slot :).

**Comment by Wimmerer** [comment] 2023-07-13 11:17
Also @lampretl Tim Davis (implementer of KLU and UMFPACK) will be there the whole week, and I'm sure he'd be happy to answer questions about this :)

**Comment by ViralBShah** [comment] 2023-07-14 16:47
Sparse matrices with low densities effectively fill up, and have fewer opportunities to use BLAS 3 etc. Sparse solvers go to tremendous lengths to get performance. To do better than the state of the art is a research problem (if possible), and certainly not an issue.

Hence, closing these issues.

**Comment by lampretl** [comment] 2023-07-14 18:52
@ViralBShah What is state-of-the-art atm for solving linear systems (in your experience)? Julia's `SparseArrays.jl`, `SuiteSparse.jl`, `LinearSolve.jl`? I'm asking because I never tried MatLab's sparse matrices, C++'s Trilinos, LinBox, Eigen, SciPy, ....

**Comment by ViralBShah** [comment] 2023-07-14 20:46
They all pretty much call the same SuiteSparse solvers under the hood. There may be differences with threading, BLAS, etc. and one should benchmark carefully and make sure we fix anything that is found to perform worse than the other systems.

**Closed** 2023-07-16 23:08 UTC

**Comment by ChrisRackauckas** [comment] 2023-07-16 23:19
Well at least the defaults are improved to prefer UMFPACK instead of KLU if the matrix is sufficiently dense.
